name: CI & CD
on:
    push:
        branches:
            - main
jobs:
    Build-and-Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Install & build
              run: |
                  npm install
                  npm run build
            - name: setup Aliyun OSS
              uses: manyuanrong/setup-ossutil@master
              with:
                  endpoint: oss-cn-shenzhen.aliyuncs.com
                  access-key-id: ${{ secrets.ACCESS_ID }}
                  access-key-secret: ${{ secrets.ACCESS_KEY }}
            - name: copy files to Aliyun
              run: ossutil cp -rf dist/ oss://allab-web/
